---
- name: Converge
  hosts: localhost
  gather_facts: no
  vars:
    client_id: "{{ lookup('env', 'UNIFIED_DOWNLOADS_API_CLIENTID') }}"
    client_secret: "{{ lookup('env', 'UNIFIED_DOWNLOADS_API_SECRET') }}"
    eap_versions:
      - version: '7.4'
        zip_pattern: '[^/]*/jboss-eap-7.4.0.zip$'
      - version: '8.1'
        zip_pattern: '[^/]*/jboss-eap-8.1.0.zip$'
  tasks:
    - name: Execute scenario if staging credentials are provided
      when:
        - client_id is defined and client_id | length > 0
        - client_secret is defined and client_secret | length > 0
      block:
        - name: Test EAP versions on staging
          include_tasks: test_stage_eap_version.yml
          loop: "{{ eap_versions }}"
          loop_control:
            loop_var: eap_version
